export enum AppModule {
  SuperAdminUserManagement = 1,
  SuperAdminLeaveManagement = 2,
  SuperAdminMonthAudit = 3,
  SuperAdminDashboard = 4,
  SuperAdminVehicleTracking = 5,
  SuperAdminVehicleManagement = 6,
  SuperAdminTripManagement = 7,
  SuperAdminReportManagement = 8,
  SuperAdminInventoryManagement = 9,
  SuperAdminProductManagement = 10,
  SuperAdminGrnManagement = 11,
  SUperAdminMonthlyExpensesManagement = 12,
  SuperAdminMasterConfiguration = 13,
  SuperAdminGarageManagement = 14,
  SuperAdminVehicleMaintenance = 15,

  AdminLeaveManagement = 30,
  AdminVehicleManagement = 31,
  AdminTripManagement = 32,
  AdminReportManagement = 33,
  AdminInventoryManagement = 34,
  AdminProductManagement = 35,
  AdminGrnManagement = 36,
  AdminMonthlyExpensesManagement = 37,
  AdminDashboard = 38,
  AdminMasterConfiguration = 39,
  AdminGarageManagement = 40,
  AdminVehicleMaintenance = 41,

  DriverLeaveManagement = 60,
  DriverTripManagement = 61,
  DriverRecomendedGarage = 62,


  TripAssistantLeaveManagement = 100,
  TripAssistantMasterConfiguration = 101,
  TripAssistantGarageManagement = 102,
  TripAssistantTripManagement = 103,
  TripAssistantVehicleMaintenance = 104,

  DriverAssistantLeaveManagement = 150,
  DriverAssistantMasterConfiguration = 151,
  DriverAssistantGarageManagement = 152,
  DriverAssistantTripManagement = 153,
  DriverAssistantVehicleMaintenance = 154,
}
